# Generated by Django 4.0 on 2024-07-18 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='data_joined',
            new_name='date_joined',
        ),
    ]
